### PR TITLE
Add helm support

### PR DESCRIPTION
**Pull request by philjackson**
Introduces a basic helm source. Makes Helm a hard dependency.

### CODE REVIEW

**Comment by philjackson** [comment]
I just saw the other pull request which looks to do almost exactly the same thing. That'll teach me...

**Comment by expez** [comment]
This looks cool!  Any idea thoughts about whether we should pick `helm` over `discover`?

**Comment by benedekfazekas** [comment]
in case this go forward can you pls squash the commits eventually

**Comment by philjackson** [comment]
There's already a cljr-helm package on melpa. Perhaps if you guys just kept `cljr--all-helpers` or similar, then I could just have that package read its candidates from clj-refactor itself. That way people can just install it if they want, and you guys don't have to bear the weight of the Helm dep.

**Comment by expez** [comment]
Sounds like a good idea :+1:

**Comment by philjackson** [comment]
Ok, back down to just the datastructure. Hopefully nothing changes for your users.

**Comment by philjackson** [comment]
I've squashed it.

**Comment by expez** [comment]
The build appears to be failing now

**Comment by philjackson** [comment]
Hurrah for tests. Fixed.

**Comment by expez** [comment]
Thanks! :+1:

**Pull request merged**
