### PR TITLE
Enable lexical scoping

### PR DESCRIPTION
**Pull request by bbatsov**
I didn't commit this directly on the slim chance that you might have done this intentionally.

### CODE REVIEW

**Comment by magnars** [comment]
Why enable lexical binding if we're not using it for anything?

**Comment by bbatsov** [comment]
> Why enable lexical binding if we're not using it for anything?

I didn't expect this as I thought the advantages were apparent. :-) E.g. - binding errors, unused vars become obvious, and a certain class of errors (accidental shadowings) become impossible. Pretty much all modern projects use lexical bindings.

**Comment by Malabarba** [comment]
It's also the least surprising option. Lexical scoping is what Clojure does, so it should be more intuitive to the developers here. :-)

**Comment by magnars** [comment]
All good reasons. Thanks!
søn. 27. mar. 2016 kl. 21.19 skrev Artur Malabarba <notifications@github.com

**Comment by benedekfazekas** [comment]
no objection here.

**Pull request merged**
