### PR TITLE
enrich `cljr--all-helpers` with type and char shortcut

### PR DESCRIPTION
**Pull request by benedekfazekas**
the enriched datastructure can be used to generate interactive helpers
for refactor commands/features more easily. the type helps to group the
commands. one command may belong to more types. the char shortcut is uniqe
for every type.

this PR aims to give a proposal to make solving #214 easier

this datastructure can be used to create `magit-popup`s for example like:
```emacs-lisp
(defun magit-action (description)
  (list (nth 2 (cdr description))
        (nth 1 (cdr description))
        (cadr description)))

(defun cljr-magit-actions (category)
  (->> cljr--all-helpers
       (-filter
        (lambda (fn-description) (-contains? (-last-item (cdr fn-description)) category)))
       (-map 'magit-action)))

(magit-define-popup
  cljr-refactor-ns-popup
  "Namespaces related cljr functions"
  :actions (cljr-magit-actions "ns"))

(magit-define-popup
  cljr-refactor-project-popup
  "Cljr functions affecting the project"
  :actions (cljr-magit-actions "project"))

(magit-define-popup
  cljr-refactor-code-popup
  "Code related cljr functions"
  :actions (cljr-magit-actions "code"))

(magit-define-popup
  cljr-refactor-toplevel-popup
  "Cljr functions changing top level forms"
  :actions (cljr-magit-actions "toplevel-form"))
```

### CODE REVIEW

**Comment by expez** [comment]
This would break `cljr-helm`.

**Comment by benedekfazekas** [comment]
possibly but even if it does should not be too difficult to fix. btw it depends on `(clj-refactor "0.13.0")`

**Comment by gregsexton** [comment]
@expez, why does this break cljr-helm? Do you rely on there being strictly only two elements in the cdr?

**Comment by expez** [comment]
Actually this line makes it look like [cljr-helm](https://github.com/philjackson/cljr-helm) is going to handle this just fine.

**Comment by benedekfazekas** [comment]
cljr-helm: :+1: ;)

**Comment by gregsexton** [comment]
I just very quickly transformed the code in to an org table and sorted by grouping and then char. I think this makes reviewing the groupings you've chosen a little easier.

    | sc | cljr-show-changelog              | Show the project's changelog                     | ?c | ("cljr")                           |
    | ?  | cljr-describe-refactoring        |                                                  | ?d | ("cljr")))                         |
    | pf | cljr-promote-function            | Promote function                                 | ?p | ("code" "toplevel-form")           |
    | cc | cljr-cycle-coll                  | Cycle coll                                       | ?c | ("code")                           |
    | dk | cljr-destructure-keys            | Destructure keys                                 | ?d | ("code")                           |
    | el | cljr-expand-let                  | Expand let                                       | ?e | ("code")                           |
    | tf | cljr-thread-first-all            | Thread first all                                 | ?f | ("code")                           |
    | ci | cljr-cycle-if                    | Cycle if                                         | ?i | ("code")                           |
    | il | cljr-introduce-let               | Introduce let                                    | ?l | ("code")                           |
    | tl | cljr-thread-last-all             | Thread last all                                  | ?L | ("code")                           |
    | ml | cljr-move-to-let                 | Move to let                                      | ?m | ("code")                           |
    | rl | cljr-remove-let                  | Remove let                                       | ?r | ("code")                           |
    | ct | cljr-cycle-thread                | Cycle thread                                     | ?t | ("code")                           |
    | th | cljr-thread                      | Thread                                           | ?T | ("code")                           |
    | ua | cljr-unwind-all                  | Unwind all                                       | ?U | ("code")                           |
    | uw | cljr-unwind                      | Unwind                                           | ?w | ("code")                           |
    | ap | cljr-add-project-dependency      | Add project dependency                           | ?p | ("ns" "project")                   |
    | cn | cljr-clean-ns                    | Clean ns                                         | ?c | ("ns")                             |
    | ai | cljr-add-import-to-ns            | Add import to ns                                 | ?i | ("ns")                             |
    | am | cljr-add-missing-libspec         | Add missing libspec                              | ?m | ("ns")                             |
    | ar | cljr-add-require-to-ns           | Add require to ns                                | ?r | ("ns")                             |
    | rr | cljr-remove-unused-requires      | Remove unused requires                           | ?R | ("ns")                             |
    | sn | cljr-sort-ns                     | Sort ns                                          | ?s | ("ns")                             |
    | sr | cljr-stop-referring              | Stop referring                                   | ?t | ("ns")                             |
    | au | cljr-add-use-to-ns               | Add use to ns                                    | ?U | ("ns")                             |
    | ru | cljr-replace-use                 | Replace use                                      | ?u | ("ns")                             |
    | rs | cljr-rename-symbol               | Rename symbol                                    | ?s | ("project" "code")                 |
    | fu | cljr-find-usages                 | Find usages                                      | ?u | ("project" "code")                 |
    | is | cljr-inline-symbol               | Inline symbol                                    | ?i | ("project" "toplevel-form" "code") |
    | rf | cljr-rename-file-or-dir          | Rename file-or-dir                               | ?r | ("project" "toplevel-form")        |
    | pc | cljr-project-clean               | Project clean                                    | ?c | ("project")                        |
    | rd | cljr-remove-debug-fns            | Remove debug fns                                 | ?d | ("project")                        |
    | hd | cljr-hotload-dependency          | Hotload dependency                               | ?h | ("project")                        |
    | sp | cljr-sort-project-dependencies   | Sort project dependencies                        | ?S | ("project")                        |
    | up | cljr-update-project-dependencies | Update project dependencies                      | ?u | ("project")                        |
    | cs | cljr-change-function-signature   | Change function signature                        | ?C | ("toplevel-form" "project")        |
    | mf | cljr-move-form                   | Move form                                        | ?m | ("toplevel-form" "project")        |
    | ec | cljr-extract-constant            | Extract constant                                 | ?c | ("toplevel-form")                  |
    | ed | cljr-extract-def                 | Extract form as def                              | ?D | ("toplevel-form")                  |
    | ad | cljr-add-declaration             | Add declaration                                  | ?d | ("toplevel-form")                  |
    | ef | cljr-extract-function            | Extract function                                 | ?e | ("toplevel-form")                  |
    | fe | cljr-create-fn-from-example      | Create function from example                     | ?f | ("toplevel-form")                  |
    | cp | cljr-cycle-privacy               | Cycle privacy                                    | ?P | ("toplevel-form")                  |
    | as | cljr-add-stubs                   | Add stubs for the interface / protocol at point. | ?s | ("toplevel-form")                  |

**Comment by benedekfazekas** [comment]
very helpful, thx! only problem is my madness of adding more types to one command here and there...

**Comment by gregsexton** [comment]
How do you envision that working with say magit popups? Just take the first one or put that refactoring in both popups? If the latter you need to make sure the key is unique in all groups that it is in.

**Comment by gregsexton** [comment]
I'm guessing you meant for a refactoring in multiple groups to be in multiple popups. If I sort the list by keybind:

    | sc | cljr-show-changelog              | Show the project's changelog                     | ?c | ("cljr")                           |
    | cc | cljr-cycle-coll                  | Cycle coll                                       | ?c | ("code")                           |
    | cn | cljr-clean-ns                    | Clean ns                                         | ?c | ("ns")                             |
    | pc | cljr-project-clean               | Project clean                                    | ?c | ("project")                        |
    | cs | cljr-change-function-signature   | Change function signature                        | ?C | ("toplevel-form" "project")        |
    | ec | cljr-extract-constant            | Extract constant                                 | ?c | ("toplevel-form")                  |
    | ?  | cljr-describe-refactoring        |                                                  | ?d | ("cljr")))                         |
    | dk | cljr-destructure-keys            | Destructure keys                                 | ?d | ("code")                           |
    | rd | cljr-remove-debug-fns            | Remove debug fns                                 | ?d | ("project")                        |
    | ed | cljr-extract-def                 | Extract form as def                              | ?D | ("toplevel-form")                  |
    | ad | cljr-add-declaration             | Add declaration                                  | ?d | ("toplevel-form")                  |
    | el | cljr-expand-let                  | Expand let                                       | ?e | ("code")                           |
    | ef | cljr-extract-function            | Extract function                                 | ?e | ("toplevel-form")                  |
    | tf | cljr-thread-first-all            | Thread first all                                 | ?f | ("code")                           |
    | fe | cljr-create-fn-from-example      | Create function from example                     | ?f | ("toplevel-form")                  |
    | hd | cljr-hotload-dependency          | Hotload dependency                               | ?h | ("project")                        |
    | ci | cljr-cycle-if                    | Cycle if                                         | ?i | ("code")                           |
    | ai | cljr-add-import-to-ns            | Add import to ns                                 | ?i | ("ns")                             |
    | is | cljr-inline-symbol               | Inline symbol                                    | ?i | ("project" "toplevel-form" "code") |
    | il | cljr-introduce-let               | Introduce let                                    | ?l | ("code")                           |
    | tl | cljr-thread-last-all             | Thread last all                                  | ?L | ("code")                           |
    | ml | cljr-move-to-let                 | Move to let                                      | ?m | ("code")                           |
    | am | cljr-add-missing-libspec         | Add missing libspec                              | ?m | ("ns")                             |
    | mf | cljr-move-form                   | Move form                                        | ?m | ("toplevel-form" "project")        |
    | pf | cljr-promote-function            | Promote function                                 | ?p | ("code" "toplevel-form")           |
    | ap | cljr-add-project-dependency      | Add project dependency                           | ?p | ("ns" "project")                   |
    | cp | cljr-cycle-privacy               | Cycle privacy                                    | ?P | ("toplevel-form")                  |
    | rl | cljr-remove-let                  | Remove let                                       | ?r | ("code")                           |
    | ar | cljr-add-require-to-ns           | Add require to ns                                | ?r | ("ns")                             |
    | rr | cljr-remove-unused-requires      | Remove unused requires                           | ?R | ("ns")                             |
    | rf | cljr-rename-file-or-dir          | Rename file-or-dir                               | ?r | ("project" "toplevel-form")        |
    | sn | cljr-sort-ns                     | Sort ns                                          | ?s | ("ns")                             |
    | rs | cljr-rename-symbol               | Rename symbol                                    | ?s | ("project" "code")                 |
    | sp | cljr-sort-project-dependencies   | Sort project dependencies                        | ?S | ("project")                        |
    | as | cljr-add-stubs                   | Add stubs for the interface / protocol at point. | ?s | ("toplevel-form")                  |
    | ct | cljr-cycle-thread                | Cycle thread                                     | ?t | ("code")                           |
    | th | cljr-thread                      | Thread                                           | ?T | ("code")                           |
    | sr | cljr-stop-referring              | Stop referring                                   | ?t | ("ns")                             |
    | ua | cljr-unwind-all                  | Unwind all                                       | ?U | ("code")                           |
    | au | cljr-add-use-to-ns               | Add use to ns                                    | ?U | ("ns")                             |
    | ru | cljr-replace-use                 | Replace use                                      | ?u | ("ns")                             |
    | fu | cljr-find-usages                 | Find usages                                      | ?u | ("project" "code")                 |
    | up | cljr-update-project-dependencies | Update project dependencies                      | ?u | ("project")                        |
    | uw | cljr-unwind                      | Unwind                                           | ?w | ("code")                           |

You can see, for example, that `i` is in the code group twice.

**Comment by benedekfazekas** [comment]
shit, you are right...

**Comment by gregsexton** [comment]
Just spotted: `u` is in project twice too. I can't see any other dups.

**Comment by gregsexton** [comment]
You could probably write a macro that validates the data structure at compile time and returns you back the input if it's good.

**Comment by benedekfazekas** [comment]
yeah fair point. validating it is a good idea deffo

**Comment by benedekfazekas** [comment]
added a checking macro. and although travis build failed for the first commit as expected it did not fail the way as expected. so does the macro make sense?

**Comment by Malabarba** [comment]
I think the first argument of -each is supposed to be a function.

**Comment by benedekfazekas** [comment]
i see `defun -each (list fn)` in my `dash.el` tho...

**Comment by Malabarba** [comment]
Nevermind then, I'm writing from a phone and couldn't check.

**Pull request merged**
