### PR TITLE
Clean trailing whitespace when removing libspecs.

### PR DESCRIPTION
**Pull request by philjackson**
Issue referenced at https://github.com/clojure-emacs/clj-refactor.el/issues/155

### CODE REVIEW

**Comment by expez** [comment]
Would you mind force pushing an updated commit message where the trailing `.` is removed and a prefix of `[Fix #155]` is added?

**Comment by philjackson** [comment]
Done.

**Comment by expez** [comment]
It seems the tests were written with the trailing whitespace in mind

**Comment by benedekfazekas** [comment]
I guess the tests need a fix in this case

**Comment by expez** [comment]
Thanks! :+1:

**Pull request merged**
