### PR TITLE
Don't force network request when initializing cache.

### PR DESCRIPTION
**Pull request by paulrd**
Before submitting a PR make sure the following things have been done (and denote this
by checking the relevant checkboxes):

- [ ] The commits are consistent with our [contribution guidelines](CONTRIBUTING.md)
- [ ] You've added tests (if possible) to cover your change(s)
- [ ] The new code is not generating byte compile warnings (run `cask exec emacs -batch -Q -L . -eval "(progn (setq byte-compile-error-on-warn t) (batch-byte-compile))" clj-refactor.el`)
- [ ] All tests are passing (run `./run-tests.sh`)
- [ ] You've updated the changelog (if adding/changing user-visible functionality)
- [ ] You've updated the readme (if adding/changing user-visible functionality)

Thanks!

### CODE REVIEW

**Comment by paulrd** [comment]
This should address #447.

**Comment by paulrd** [comment]
I wasn't able to figure out how to ./run-tests.sh or (run cask exec emacs -batch -Q -L . -eval "(progn (setq byte-compile-error-on-warn t) (batch-byte-compile))" clj-refactor.el)

**Comment by paulrd** [comment]
./run-tests.sh result:
cask exec: error: Failed to execute ecukes --no-win: [Errno 2] No such file or directory
Did you run cask install?

**Comment by expez** [comment]
Thanks @paulrd! 👍

**Pull request merged**
