### PR TITLE
[Fix #101] Add cljr-inline-symbol

### LINKED ISSUE #101: Inlining
I'd like to be able to inline

* let-bound variables
* vars
* functions

A function would turn into the `fn` form and then we can consider adding `cljr-demote-function` to turn an `fn` into a function literal.

### PR DESCRIPTION
**Pull request by expez**
Make it possible to inline:

- def
- defn
- let-bound vars

This is bound to is

### CODE REVIEW

**Comment by benedekfazekas** [comment]
nice! 

bit of explanation/description/animgif would not hurt tho...

**Comment by expez** [comment]
I did some work on the wiki last week, I really want to get everything up in there, but I haen't found a good way to record gifs on linux :(

**Comment by benedekfazekas** [comment]
i anyway want to try it so will do in the afternoon

**Comment by arichiardi** [comment]
For recording, there is [this](http://askubuntu.com/a/201018) and thanks for having implemented this feature!

**Comment by expez** [comment]
Thanks for the tip @arichiardi!

**Pull request merged**
