### PR TITLE
Fix wrong REPL error output function name

### PR DESCRIPTION
**Pull request by zarkone**
today after update i found this error after connecting to REPL. this fix seems to fix this.
(https://github.com/clojure-emacs/cider/commit/d81b77a5575c6efe59e7c94de0bc6c3c2504c12c)

### CODE REVIEW

**Comment by expez** [comment]
Great!

Thanks for spotting this! :+1: 

Could you update the commit message so it complies with our [guidelines](https://github.com/clojure-emacs/clj-refactor.el/blob/master/CONTRIBUTING.md)?

**Comment by zarkone** [comment]
thanks @expez, tried better now.

**Comment by expez** [comment]
sorry!

Could you also drop the period from the end of the commit message?

**Comment by zarkone** [comment]
@expez i just need time to become more attentive and intent. At least I believe in this :)

**Comment by expez** [comment]
Thanks again, @zarkone! :+1:

**Pull request merged**
