### PR TITLE
Remove cycle privacy, cycle if, cycle collection

### PR DESCRIPTION
**Pull request by benedekfazekas**
because they are moved to Clojure mode. Add minimum clojure-mode
version (20160604), keep old mnemonics for the first two features and
point them to the clojure-mode functions. Also remove cycle collection
entirely as it got reworked into convert into collection type in Clojure mode.

- [x] The commits are consistent with our [contribution guidelines](CONTRIBUTING.md)
- [x] You've added tests (if possible) to cover your change(s)
- [x] The new code is not generating byte compile warnings (run `cask exec emacs -batch -Q -L . -eval "(progn (setq byte-compile-error-on-warn t) (batch-byte-compile))" clj-refactor.el`)
- [x] All tests are passing (run `./run-tests.sh`)
- [x] You've updated the changelog (if adding/changing user-visible functionality)
- [x] You've updated the readme (if adding/changing user-visible functionality)

As the related change got merged into clojure mode a week ago deadline for this is next Sunday.

### CODE REVIEW

**Comment by Malabarba** [comment]
> Also remove cycle collection
entirely as it got reworked into convert into collection type in Clojure mode.

It's up to you, but it might be good to keep this command. I just know there someone who's gonna complain they liked the old one better.

**Comment by expez** [comment]
LGTM :+1:

**Comment by benedekfazekas** [comment]
@Malabarba I was considering keeping the cycle collection types here by rewriting the function so it calls the right fns in Clojure mode. Still happy to do it but thinking that the new solution is actually better in the sense of being simpler than cycling. So why not push users towards it a bit?

**Comment by Malabarba** [comment]
> I was considering keeping the cycle collection types here by rewriting the function so it calls the right fns in Clojure mode. 

Nah, I think it's not worth the trouble.

**Pull request merged**
