### PR TITLE
Add cljr-change-function-signature

### PR DESCRIPTION
**Pull request by expez**
Refactor the function signature of the function at point.  Supports both
changing the order and name of the function's parameters.

### CODE REVIEW

**Comment by expez** [comment]
.This feature needs a bunch of tests, but I'd like som feedback at this point.

The user is presented with a buffer containing the function parameters.  In this buffer the user can use `M-n` or `M-p` to move the parameters of the parameter list or `C-c C-e` to change the name of a parameter.  When the user is satisfied with her changes she can press `C-c C-c` to commit and we go off an update all call-sites.  There's also `C-c C-k` to abort.

Most call-sites can be handled automatically (regular calls, in addition to `apply` and `partial`), but for those we can't handle the entry is added to a buffer containing stuff which needs manual intervention.  This buffer is a `grep` buffer much like the buffer for `find-usages` where the user can easily jump around.

**Comment by benedekfazekas** [comment]
nice one! I will try to give it a spin in the evening..

**Comment by Malabarba** [comment]
Sounds like a great feature. Since the signatures buffer is in view mode, would it make sense to also offer unprefixed keys on it? Like q, e, and RET, to respectively quit, edit, and confirm.

**Comment by expez** [comment]
> Sounds like a great feature. Since the signatures buffer is in view mode, would it make sense to also offer unprefixed keys on it? Like q, e, and RET, to respectively quit, edit, and confirm.

Great idea!

**Comment by expez** [comment]
@magnars any thoughts about these test failures?  I haven't touched any code related to the failures and it's all green locally :/

**Comment by magnars** [comment]
Hmm. Seems like `project-clean` and `move-form` are failing. They both use `remove-unused-requires` - has that been changed?

**Pull request merged**
